objects/PPCommonRequestParameters__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationName__c</fullName>
        <description>Your Application&apos;s Identification, such as the name of your application.</description>
        <inlineHelpText>Your Application&apos;s Identification, such as the name of your application.</inlineHelpText>
        <label>ApplicationName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <description>The currency code</description>
        <inlineHelpText>The currency code</inlineHelpText>
        <label>CurrencyCode</label>
        <picklist>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HKD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MXN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TWD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DetailLevel__c</fullName>
        <description>The level of detail required by the client application for component such as Item, Transaction.</description>
        <inlineHelpText>The level of detail required by the client application for component such as Item, Transaction.</inlineHelpText>
        <label>DetailLevel</label>
        <picklist>
            <picklistValues>
                <fullName>ReturnAll</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FeePayer__c</fullName>
        <description>The payer of PayPal fees</description>
        <inlineHelpText>The payer of PayPal fees</inlineHelpText>
        <label>FeePayer</label>
        <picklist>
            <picklistValues>
                <fullName>SENDER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRIMARYRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EACHRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECONDARYONLY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PayPal Common Request Parameters</label>
    <nameField>
        <label>PPCommonRequestParameters Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PayPal Common Request Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PPPreapprovalRequestTest.cls
@isTest 
private class PPPreapprovalRequestTest {
	static testMethod void testGetRequestParams() {
        PPPreapprovalRequest request = new PPPreapprovalRequest();
        request.setRequestEnvelopeParams('en_US', '');
        System.assert(request.RequestEnvelope != Null);
        System.assert(request.RequestEnvelope.ErrorLanguage.equals('en_US'));
        System.assert(request.RequestEnvelope.DetailLevelCode.equals(PPStaticRes.DEFAULT_DETAIL_LEVEL_CODE));
        
        request.cancelUrl = 'https://c.ap1.visual.force.com/apex/CancelURL';
        request.returnUrl = 'https://c.ap1.visual.force.com/apex/ReturnURL';
        PPClientDetails clientDetails = new PPClientDetails();
        clientDetails.applicationId = 'myapp';
        clientDetails.ipAddress = '172.16.4.89';
        request.clientDetails = clientDetails;
        request.CurrencyCode = 'USD';
        request.DateOfMonth = 1;
        request.DayOfWeek = 'WEDNESDAY';
        request.EndingDate = DateTime.newInstance(2009, 10, 9);
        request.MaxAmountPerPayment = 10;
        request.MaxNumberOfPayments =  5;
        request.MaxNumberOfPaymentsPerPeriod = 1;
        request.maxTotalAmountOfAllPayment = 100;
        request.PaymentPeriod = 'DAILY';
        request.PinType = 'NOT_REQUIRED';
        request.StartingDate = DateTime.newInstance(2009, 9, 20);
     	request.IpnNotificationUrl = 'http:\\www.ipnURl';
     	request.Memo = 'Memo';
     	request.SenderEmail = 'sonali@persistent.co.in';
     	
     	System.assert(request.clientDetails != Null);
     	System.assert(request.clientDetails.IpAddress.equals('172.16.4.89'));
     	System.assert(request.clientDetails.applicationId.equals('myapp'));
     	System.assert(request.CurrencyCode.equals('USD'));
     	System.assert(request.DateOfMonth == 1);
     	System.assert(request.DayOfWeek.equals('WEDNESDAY'));
     	System.assert(request.EndingDate != Null);
     	System.assert(request.MaxAmountPerPayment == 10);
     	System.assert(request.MaxNumberOfPayments == 5);
     	System.assert(request.MaxNumberOfPaymentsPerPeriod == 1);
     	System.assert(request.PaymentPeriod.equals('DAILY'));
     	System.assert(request.PinType.equals('NOT_REQUIRED'));
     	System.assert(request.StartingDate != Null);
     	System.assert(request.IpnNotificationUrl.equals('http:\\www.ipnURl'));
     	System.assert(request.SenderEmail.equals('sonali@persistent.co.in'));
     	System.assert(request.Memo.equals('Memo'));
     	
     	
     	Map<String, String> params = new Map<String, String>();
		request.getRequestParams(params);
		
		System.assert(params.get(PPStaticRes.CLIENT_DETAILS + PPStaticRes.DOT + PPStaticRes.IP_ADDRESS).equals('172.16.4.89'));
		System.assert(params.get(PPStaticRes.CLIENT_DETAILS + PPStaticRes.DOT + PPStaticRes.APPLICATION_ID).equals('myapp'));
		System.assert(params.get(PPStaticRes.CANCEL_URL).equals('https://c.ap1.visual.force.com/apex/CancelURL'));
		System.assert(params.get(PPStaticRes.RETURN_URL).equals('https://c.ap1.visual.force.com/apex/ReturnURL'));
		System.assert(params.get(PPStaticRes.CURRENCY_CODE).equals('USD'));
		System.assert(params.get(PPStaticRes.IPN_NOTIFICATION_URL).equals('http:\\www.ipnURl'));
		System.assert(params.get(PPStaticRes.MEMO).equals('Memo'));
		System.assert(params.get(PPStaticRes.SENDER_EMAIL).equals('sonali@persistent.co.in'));
		System.assert(params.get(PPStaticRes.REQUEST_ENVELOPE + PPStaticRes.DOT + PPStaticRes.ERROR_LANGUAGE).equals('en_US'));
		System.assert(params.get(PPStaticRes.REQUEST_ENVELOPE + PPStaticRes.DOT + PPStaticRes.DETAIL_LEVEL_CODE).equals('ReturnAll'));
		System.assert(params.get(PPStaticRes.DATE_OF_MONTH).equals('1'));
		System.assert(params.get(PPStaticRes.DAY_OF_WEEK).equals('WEDNESDAY'));
		System.assert(params.get(PPStaticRes.ENDING_DATE).equals((DateTime.newInstance(2009, 10, 9)).format('yyyy-MM-dd')));
		System.assert(params.get(PPStaticRes.MAX_AMOUNT_PER_PAYMENT).equals('10'));
		System.assert(params.get(PPStaticRes.MAX_NUMBER_OF_PAYMENTS).equals('5'));
		System.assert(params.get(PPStaticRes.MAX_NUMBER_OF_PAYMENTS_PER_PERIOD).equals('1'));
		System.assert(params.get(PPStaticRes.MAX_TOTAL_AMOUNT_OF_ALL_PAYMENTS).equals('100'));
		System.assert(params.get(PPStaticRes.PAYMENT_PERIOD).equals('DAILY'));
		System.assert(params.get(PPStaticRes.PIN_TYPE).equals('NOT_REQUIRED'));
		System.assert(params.get(PPStaticRes.STARTING_DATE).equals(DateTime.newInstance(2009, 9, 20).format('yyyy-MM-dd')));
	}
	
	static testMethod void testGetRequestParams2() {
        // test cases for 3_TOKEN Credentials
		PPCommonRequestParameters__c t1 = new PPCommonRequestParameters__c(  ApplicationName__c='DUMMY-APP',CurrencyCode__c='USD',DetailLevel__c='ReturnAll',FeePayer__c='SENDER',Language__c='en_US', name='test' );
		insert t1;
		
		PPPreapprovalRequest request = new PPPreapprovalRequest('test', 'sonali@persistent.co.in');
		
        System.assert(request.RequestEnvelope != Null);
        System.assert(request.RequestEnvelope.ErrorLanguage.equals('en_US'));
        System.assert(request.RequestEnvelope.DetailLevelCode.equals(PPStaticRes.DEFAULT_DETAIL_LEVEL_CODE));
        
        request.cancelUrl = 'https://c.ap1.visual.force.com/apex/CancelURL';
        request.returnUrl = 'https://c.ap1.visual.force.com/apex/ReturnURL';
        request.CurrencyCode = 'USD';
        request.DateOfMonth = 1;
        request.DayOfWeek = 'WEDNESDAY';
        request.EndingDate = DateTime.newInstance(2009, 10, 9);
        request.MaxAmountPerPayment = 10;
        request.MaxNumberOfPayments =  5;
        request.MaxNumberOfPaymentsPerPeriod = 1;
        request.maxTotalAmountOfAllPayment = 100;
        request.PaymentPeriod = 'DAILY';
        request.PinType = 'NOT_REQUIRED';
        request.StartingDate = DateTime.newInstance(2009, 9, 20);
     	request.IpnNotificationUrl = 'http:\\www.ipnURl';
     	request.Memo = 'Memo';
     	
     	System.assert(request.clientDetails != Null);
     	System.assert(request.clientDetails.applicationId.equals('DUMMY-APP'));
     	System.assert(request.CurrencyCode.equals('USD'));
     	System.assert(request.DateOfMonth == 1);
     	System.assert(request.DayOfWeek.equals('WEDNESDAY'));
     	System.assert(request.EndingDate != Null);
     	System.assert(request.MaxAmountPerPayment == 10);
     	System.assert(request.MaxNumberOfPayments == 5);
     	System.assert(request.MaxNumberOfPaymentsPerPeriod == 1);
     	System.assert(request.PaymentPeriod.equals('DAILY'));
     	System.assert(request.PinType.equals('NOT_REQUIRED'));
     	System.assert(request.StartingDate != Null);
     	System.assert(request.IpnNotificationUrl.equals('http:\\www.ipnURl'));
     	System.assert(request.SenderEmail.equals('sonali@persistent.co.in'));
     	System.assert(request.Memo.equals('Memo'));
     	
     	
     	Map<String, String> params = new Map<String, String>();
		request.getRequestParams(params);
		
		System.assert(params.get(PPStaticRes.CLIENT_DETAILS + PPStaticRes.DOT + PPStaticRes.APPLICATION_ID).equals('DUMMY-APP'));
		System.assert(params.get(PPStaticRes.CANCEL_URL).equals('https://c.ap1.visual.force.com/apex/CancelURL'));
		System.assert(params.get(PPStaticRes.RETURN_URL).equals('https://c.ap1.visual.force.com/apex/ReturnURL'));
		System.assert(params.get(PPStaticRes.CURRENCY_CODE).equals('USD'));
		System.assert(params.get(PPStaticRes.IPN_NOTIFICATION_URL).equals('http:\\www.ipnURl'));
		System.assert(params.get(PPStaticRes.MEMO).equals('Memo'));
		System.assert(params.get(PPStaticRes.SENDER_EMAIL).equals('sonali@persistent.co.in'));
		System.assert(params.get(PPStaticRes.REQUEST_ENVELOPE + PPStaticRes.DOT + PPStaticRes.ERROR_LANGUAGE).equals('en_US'));
		System.assert(params.get(PPStaticRes.REQUEST_ENVELOPE + PPStaticRes.DOT + PPStaticRes.DETAIL_LEVEL_CODE).equals('ReturnAll'));
		System.assert(params.get(PPStaticRes.DATE_OF_MONTH).equals('1'));
		System.assert(params.get(PPStaticRes.DAY_OF_WEEK).equals('WEDNESDAY'));
		System.assert(params.get(PPStaticRes.ENDING_DATE).equals((DateTime.newInstance(2009, 10, 9)).format('yyyy-MM-dd')));
		System.assert(params.get(PPStaticRes.MAX_AMOUNT_PER_PAYMENT).equals('10'));
		System.assert(params.get(PPStaticRes.MAX_NUMBER_OF_PAYMENTS).equals('5'));
		System.assert(params.get(PPStaticRes.MAX_NUMBER_OF_PAYMENTS_PER_PERIOD).equals('1'));
		System.assert(params.get(PPStaticRes.MAX_TOTAL_AMOUNT_OF_ALL_PAYMENTS).equals('100'));
		System.assert(params.get(PPStaticRes.PAYMENT_PERIOD).equals('DAILY'));
		System.assert(params.get(PPStaticRes.PIN_TYPE).equals('NOT_REQUIRED'));
		System.assert(params.get(PPStaticRes.STARTING_DATE).equals(DateTime.newInstance(2009, 9, 20).format('yyyy-MM-dd')));
	}
}