objects/Sphero_Message__c.object
<CustomObject>
    <description>Sphero Message to store sphero bucks and sphero name.</description>
    <fields>
        <fullName>Bucks__c</fullName>
        <description>The Bucks the sphero is making.</description>
        <label>Bucks</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sphero_Name__c</fullName>
        <label>Sphero_Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sphero Message</label>
    <nameField>
        <displayFormat>SM-{00000}</displayFormat>
        <label>Sphero Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sphero Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpheroTest.cls
@isTest
public class SpheroTest{

    static testmethod void testSphero() {
    	//should result in a new sphero message
        SpheroController.create('rgb','128');
        List<Sphero_Message__c> messages = [Select Id, Name, Sphero_Name__c, Bucks__c From Sphero_Message__c where Sphero_Name__c = 'rgb'];
        System.assertEquals(1, messages.size());
    }
    
//    static testmethod void test_BadSphero() {
//        SpheroController.create('rgb-11111122222333334444455555','tmp36');
//       List<Sphero_Message__c> messages = [Select Id, Name, Sphero_Name__c, Bucks__c From Sphero_Message__c where Sphero_Name__c = 'rgb-11111122222333334444455555'];
//        System.assertNotEquals(1, messages.size());
//    }    
        
}