objects/Sphero_Message__c.object
<CustomObject>
    <description>Sphero Message to store sphero bucks and sphero name.</description>
    <fields>
        <fullName>Bucks__c</fullName>
        <description>The Bucks the sphero is making.</description>
        <label>Bucks</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sphero_Name__c</fullName>
        <label>Sphero_Name</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sphero Message</label>
    <nameField>
        <displayFormat>SM-{00000}</displayFormat>
        <label>Sphero Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sphero Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpheroController.cls
@RestResource(urlMapping='/SpheroController/*')
global with sharing class SpheroController {
    @HttpPost
        global static void create(String spheroName, String bucks) {
            SpheroController.handleSpheroMessage(spheroName, bucks);
        }
    
    public static void handleSpheroMessage(String spheroName, String bucks) {
        Sphero_Message__c sm = new Sphero_Message__c();
        sm.Sphero_Name__c = spheroName;
        sm.Bucks__c = bucks;
        insert sm;
    }
}