objects/UniqueMail__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>メールアドレス</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WishAccounts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>会計・財務関連サービスの案内を希望</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WishExam__c</fullName>
        <defaultValue>false</defaultValue>
        <label>試験・研修の案内を希望</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WishSeminarEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>セミナー・イベントの案内を希望</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WishWEBContents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WEBコンテンツの案内を希望</label>
        <type>Checkbox</type>
    </fields>
    <label>ユニークメールアドレス</label>
    <nameField>
        <label>ユニークメールアドレス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OptOutController.cls
public without sharing class OptOutController {

    public OptOutController(ApexPages.StandardController controller) {
        this.um = [Select Name, Email__c, WishWEBContents__c, WishAccounts__c, WishSeminarEvent__c, WishExam__c From UniqueMail__c Where Id=: ApexPages.currentPage().getParameters().get('id')];   
        this.logs =  String.valueOf(this.um);
    }
    
    public UniqueMail__c um{get;set;}
    public String logs{get;set;}
    
    public PageReference save(){
        update um;
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, '保存しました。'));
        
        return null;
    }
    
}